In [3]:
import numpy as np  # 导入numpy包并将其命名为np


In [4]:
##定义正向化的函数
def positivization(x,type,i):
# x：需要正向化处理的指标对应的原始向量
# typ：指标类型（1：极小型，2：中间型，3：区间型）
# i：正在处理的是原始矩阵的哪一列
    if type == 1:  #极小型
        print("第",i,"列是极小型，正向化中...")
        posit_x = x.max(0)-x
        print("第",i,"列极小型处理完成")
        print("--------------------------分隔--------------------------")
        return posit_x
    elif type == 2:  #中间型
        print("第",i,"列是中间型")
        best = int(input("请输入最佳值：\n"))
        m = (abs(x-best)).max()
        posit_x = 1-abs(x-best)/m
        print("第",i,"列中间型处理完成")
        print("--------------------------分隔--------------------------")
        return posit_x
    elif type == 3:  #区间型
        print("第",i,"列是区间型")
        a,b = [int(l) for l in input("按顺序输入最佳区间的左右界，并用逗号隔开：\n").split(",")]
        m = (np.append(a-x.min(),x.max()-b)).max()
        x_row = x.shape[0]  #获取x的行数
        posit_x = np.zeros((x_row,1),dtype=float)
        for r in range(x_row):
            if x[r] < a:
               posit_x[r] = 1-(a-x[r])/m
            elif x[r] > b:
               posit_x[r] = 1-(x[r]-b)/m
            else:
               posit_x[r] = 1
        print("第",i,"列区间型处理完成")
        print("--------------------------分隔--------------------------")
        return posit_x.reshape(x_row)

In [5]:
## 第一步：从外部导入数据
#注：保证表格不包含除数字以外的内容
x_mat = np.loadtxt('river.csv', encoding='UTF-8-sig', delimiter=',')  # 推荐使用csv格式文件
x_mat

array([[ 4.69,  6.59, 51.  , 11.94],
       [ 2.03,  7.86, 19.  ,  6.46],
       [ 9.11,  6.31, 46.  ,  8.91],
       [ 8.61,  7.05, 46.  , 26.43],
       [ 7.13,  6.5 , 50.  , 23.57],
       [ 2.39,  6.77, 38.  , 24.62],
       [ 7.69,  6.79, 38.  ,  6.01],
       [ 9.3 ,  6.81, 27.  , 31.57],
       [ 5.45,  7.62,  5.  , 18.46],
       [ 6.19,  7.27, 17.  ,  7.51],
       [ 7.93,  7.53,  9.  ,  6.52],
       [ 4.4 ,  7.28, 17.  , 25.3 ],
       [ 7.46,  8.24, 23.  , 14.42],
       [ 2.01,  5.55, 47.  , 26.31],
       [ 2.04,  6.4 , 23.  , 17.91],
       [ 7.73,  6.14, 52.  , 15.72],
       [ 6.35,  7.58, 25.  , 29.46],
       [ 8.29,  8.41, 39.  , 12.02],
       [ 3.54,  7.27, 54.  ,  3.16],
       [ 7.44,  6.26,  8.  , 28.41]])

In [6]:
## 第二步：判断是否需要正向化
n, m = x_mat.shape
print("共有", n, "个评价对象", m, "个评价指标")
judge = int(input("指标是否需要正向化处理，需要请输入1，不需要则输入0：\n"))
if judge == 1:
    position = np.array([int(i) for i in input("请输入需要正向化处理的指标所在的列，例如第1、3、4列需要处理，则输入1,3,4：\n").split(',')])
    position = position-1
    typ = np.array([int(j) for j in input("请按照顺序输入这些列的指标类型（1：极小型，2：中间型，3：区间型）格式同上：\n").split(',')])
    for k in range(position.shape[0]):
        x_mat[:, position[k]] = positivization(x_mat[:, position[k]], typ[k], position[k])
    print("正向化后的矩阵：\n", x_mat)

共有 20 个评价对象 4 个评价指标
第 1 列是中间型
第 1 列中间型处理完成
--------------------------分隔--------------------------
第 2 列是极小型，正向化中...
第 2 列极小型处理完成
--------------------------分隔--------------------------
第 3 列是区间型
第 3 列区间型处理完成
--------------------------分隔--------------------------
正向化后的矩阵：
 [[4.69000000e+00 7.17241379e-01 3.00000000e+00 1.00000000e+00]
 [2.03000000e+00 4.06896552e-01 3.50000000e+01 6.94036301e-01]
 [9.11000000e+00 5.24137931e-01 8.00000000e+00 9.05790838e-01]
 [8.61000000e+00 9.65517241e-01 8.00000000e+00 4.44252377e-01]
 [7.13000000e+00 6.55172414e-01 4.00000000e+00 6.91443388e-01]
 [2.39000000e+00 8.41379310e-01 1.60000000e+01 6.00691443e-01]
 [7.69000000e+00 8.55172414e-01 1.60000000e+01 6.55142610e-01]
 [9.30000000e+00 8.68965517e-01 2.70000000e+01 0.00000000e+00]
 [5.45000000e+00 5.72413793e-01 4.90000000e+01 1.00000000e+00]
 [6.19000000e+00 8.13793103e-01 3.70000000e+01 7.84788245e-01]
 [7.93000000e+00 6.34482759e-01 4.50000000e+01 6.99222126e-01]
 [4.40000000e+00 8.06896552e-01 3.7

In [7]:
## 第三步：对正向化后的矩阵进行标准化
tep_x1 = (x_mat * x_mat).sum(axis=0)  # 每个元素平方后按列相加
tep_x2 = np.tile(tep_x1, (n, 1))  # 将矩阵tep_x1平铺n行
Z = x_mat / ((tep_x2) ** 0.5)  # Z为标准化矩阵
print("标准化后的矩阵为：\n", Z)

标准化后的矩阵为：
 [[0.16218592 0.24825528 0.02454403 0.30645756]
 [0.07019987 0.14083713 0.28634707 0.21269267]
 [0.3150349  0.18141732 0.06545076 0.27758645]
 [0.29774429 0.3341898  0.06545076 0.1361445 ]
 [0.24656409 0.22677165 0.03272538 0.21189806]
 [0.08264911 0.29122254 0.13090152 0.18408644]
 [0.26592957 0.29599668 0.13090152 0.20077341]
 [0.32160534 0.30077082 0.22089631 0.        ]
 [0.18846764 0.19812681 0.4008859  0.30645756]
 [0.21405774 0.28167426 0.30270976 0.24050429]
 [0.27422907 0.21961044 0.36816052 0.21428191]
 [0.15215736 0.27928719 0.30270976 0.1660751 ]
 [0.25797589 0.05012847 0.25362169 0.30645756]
 [0.06950825 0.         0.05726941 0.13932297]
 [0.07054569 0.20290095 0.25362169 0.30645756]
 [0.26731282 0.14083713 0.01636269 0.30645756]
 [0.21959074 0.20767509 0.237259   0.05588811]
 [0.2866783  0.00954828 0.12272017 0.30645756]
 [0.12241751 0.28167426 0.         0.12528473]
 [0.25728427 0.16948197 0.37634187 0.08369973]]


In [9]:
## 第四步：计算与最大值和最小值的距离，并算出得分
tep_max = Z.max(0)  # 得到Z中每列的最大值
tep_min = Z.min(0)  # 每列的最小值
tep_a = Z - np.tile(tep_max, (n, 1))  # 将tep_max向下平铺n行,并与Z中的每个对应元素做差
tep_i = Z - np.tile(tep_min, (n, 1))  # 将tep_max向下平铺n行，并与Z中的每个对应元素做差
D_P = ((tep_a ** 2).sum(axis=1)) ** 0.5  # D+与最大值的距离向量
D_N = ((tep_i ** 2).sum(axis=1)) ** 0.5
S = D_N / (D_P + D_N)  # 未归一化的得分
std_S = S / S.sum(axis=0)
sorted_S = sorted(std_S,reverse=True)
print(std_S)  # 打印标准化后的得分
print(sorted_S)
print(np.argsort(-std_S)+1)
np.savetxt('std_S.csv',std_S,delimiter=',') #结果输出到std_S.csv文件


[0.04505807 0.04779877 0.0484974  0.04882021 0.04311311 0.04483784
 0.05394726 0.05099837 0.06807383 0.06839331 0.07016173 0.05909344
 0.05265184 0.01919585 0.05330661 0.04335862 0.04657437 0.04384359
 0.03580976 0.05646602]
[0.07016173211984317, 0.06839330659786512, 0.06807383242237745, 0.059093442016977325, 0.056466023050463436, 0.0539472609170102, 0.053306610561304556, 0.05265184418973397, 0.05099836955485169, 0.048820212370091244, 0.04849739980324669, 0.04779877012911279, 0.04657436832957741, 0.04505806649931113, 0.04483783522204978, 0.04384358801036158, 0.043358618664056325, 0.0431131054709501, 0.03580976122667384, 0.01919585284414206]
[11 10  9 12 20  7 15 13  8  4  3  2 17  1  6 18 16  5 19 14]
