# 匈牙利算法

In [2]:
# 匈牙利算法
from scipy.optimize import linear_sum_assignment
import numpy as np


cost =np.array([[4,1,3],[2,0,5],[3,2,2]])
row_ind,col_ind=linear_sum_assignment(cost)
print(row_ind)#开销矩阵对应的行索引
print(col_ind)#对应行索引的最优指派的列索引
print(cost[row_ind,col_ind])#提取每个行索引的最优指派列索引所在的元素，形成数组
print(cost[row_ind,col_ind].sum())#数组求和

[0 1 2]
[1 0 2]
[1 2 2]
5


https://vimsky.com/examples/usage/python-scipy.optimize.linear_sum_assignment.html

## 蒙特卡洛法

In [6]:
import random
def f(x: list) -> int:
    return x[0] ** 2 + x[1] ** 2 + 3 * x[2] ** 2 + 4 * x[3] ** 2 + 2 * x[4] ** 2 - 8 * x[0] - 2 * x[1] - 3 * x[2]-x[3]-2 * x[4]

def g(x: list) -> list:
    res = []
    res.append(sum(x) - 400)
    res.append(x[0] + 2 * x[1] + 2 * x[2] + x[3] + 6 * x[4] - 800)
    res.append(2 * x[0] + x[1] + 6 * x[2] - 200)
    res.append(x[2] + x[3] + 5 * x[4] - 200)
    return res

max = 0
xlist = []
random.seed(1)
for i in range(10 ** 6):
    x = [random.randint(0, 99) for i in range(5)]       # 产生一行五列的区间[0, 99] 上的随机整数
    rf = f(x)
    rg = g(x)
    if all((a < 0 for a in rg)):        # 若 rg 中所有元素都小于 0
        if max <rf:
            xlist= x
            max = rf
print(xlist, max)

[48, 99, 0, 99, 7] 50712
