In [1]:
from scipy.sparse.linalg import eigs
from numpy import array, hstack




a=array([[1,1/2,5,5,3],[2,1,7,7,5],[1/5,1/7,1,1/2,1/3],
        [1/5,1/7,2,1,1/2],[1/3,1/5,3,2,1]])
L,V=eigs(a,1);
CR=(L-5)/4/1.12  #计算矩阵A的一致性比率
W=V/sum(V); print("最大特征值为：",L)
print("最大特征值对应的特征向量W=\n",W)
print("CR=",CR)
B1=array([[1,1/3,1/2],[3,1,1/2],[2,2,1]])
L1,P1=eigs(B1,1); P1=P1/sum(P1)
print("P1=",P1)
B2=array([[1,3,2],[1/3,1,2],[1/2,1/2,1]])
t2,P2=eigs(B2,1); P2=P2/sum(P2)
print("P2=",P2)
B3=array([[1,4,3],[1/4,1,2],[1/3,1/2,1]])
t3, P3=eigs(B3,1); P3=P3/sum(P3)
print("P3=",P3)
B4=array([[1,3,2],[1/3,1,2],[1/2,1/2,1]])
t4, P4=eigs(B4,1); P4=P4/sum(P4)
print("P4=", P4)
B5=array([[1,2,3],[1/2,1,1/2],[1/3,2,1]])
t5, P5=eigs(B5,1); P5=P5/sum(P5)
print("P5=",P5)
K=hstack([P1,P2,P3,P4,P5])@W  #矩阵乘法
print("K=",K)

最大特征值为： [5.09758844+0.j]
最大特征值对应的特征向量W=
 [[0.28626525-0.j]
 [0.48093287-0.j]
 [0.04851865-0.j]
 [0.0685439 -0.j]
 [0.11573932-0.j]]
CR= [0.02178313+0.j]
P1= [[0.16765631-0.j]
 [0.34873919-0.j]
 [0.4836045 -0.j]]
P2= [[0.54721643-0.j]
 [0.26307422-0.j]
 [0.18970934-0.j]]
P3= [[0.63009766-0.j]
 [0.21844266-0.j]
 [0.15145968-0.j]]
P4= [[0.54721643+0.j]
 [0.26307422+0.j]
 [0.18970934+0.j]]
P5= [[0.54721643-0.j]
 [0.18970934-0.j]
 [0.26307422-0.j]]
K= [[0.44258285+0.j]
 [0.27694046+0.j]
 [0.28047669+0.j]]


In [2]:
import numpy as np
import pandas as pd




a=np.loadtxt("./数据集/Pdata9_1_1.txt",)
R1=a.copy(); R2=a.copy(); R3=a.copy()  #初始化
#注意R1=a,它们的内存地址一样，R1改变时，a也改变
for j in [0,1,2,4,5]:
    R1[:,j]=R1[:,j]/np.linalg.norm(R1[:,j]) #向量归一化
    R2[:,j]=R1[:,j]/max(R1[:,j])     #比例变换
    R3[:,j]=(R3[:,j]-min(R3[:,j]))/(max(R3[:,j])-min(R3[:,j]));
R1[:,3]=1-R1[:,3]/np.linalg.norm(R1[:,3])
R2[:,3]=min(R2[:,3])/R2[:,3]
R3[:,3]=(max(R3[:,3])-R3[:,3])/(max(R3[:,3])-min(R3[:,3]))
np.savetxt("./数据集/Pdata9_1_2.txt", R1); #把数据写入文本文件，供下面使用
np.savetxt("./数据集/Pdata9_1_3.txt", R2); np.savetxt("./数据集/Pdata9_1_4.txt", R3)
DR1=pd.DataFrame(R1)  #生成DataFrame类型数据
DR2=pd.DataFrame(R2); DR3=pd.DataFrame(R3)
f=pd.ExcelWriter('./数据集/Pdata9_1_5.xlsx')  #创建文件对象
DR1.to_excel(f,"sheet1")  #把DR1写入Excel文件1号表单中,方便做表
DR2.to_excel(f,"sheet2"); DR3.to_excel(f, "Sheet3"); f.save()

In [3]:
import numpy as np
from scipy.stats import rankdata



a=np.loadtxt("./数据集/Pdata9_1_3.txt")

cplus=a.max(axis=0)   #逐列求最大值
cminus=a.min(axis=0)  #逐列求最小值
print("正理想解=",cplus,"负理想解=",cminus)
d1=np.linalg.norm(a-cplus, axis=1)  #求到正理想解的距离
d2=np.linalg.norm(a-cminus, axis=1) #求到负理想解的距离
print(d1, d2)   #显示到正理想解和负理想解的距离
f1=d2/(d1+d2); print("TOPSIS的评价值为：", f1)

t=cplus-a   #计算参考序列与每个序列的差
mmin=t.min(); mmax=t.max()  #计算最小差和最大差
rho=0.5  #分辨系数
xs=(mmin+rho*mmax)/(t+rho*mmax)  #计算灰色关联系数
f2=xs.mean(axis=1)  #求每一行的均值
print("\n关联系数=", xs,'\n关联度=',f2)  #显示灰色关联系数和灰色关联度

[n, m]=a.shape
cs=a.sum(axis=0)  #逐列求和
P=1/cs*a   #求特征比重矩阵
e=-(P*np.log(P)).sum(axis=0)/np.log(n)  #计算熵值
g=1-e   #计算差异系数
w = g / sum(g)  #计算权重
F = P @ w       #计算各对象的评价值
print("\nP={}\n,e={}\n,g={}\n,w={}\nF={}".format(P,e,g,w,F))

R=[rankdata(a[:,i]) for i in np.arange(6)]  #求每一列的秩
R=np.array(R).T   #构造秩矩阵
print("\n秩矩阵为：\n",R)
RSR=R.mean(axis=1)/n; print("RSR=", RSR)

正理想解= [1. 1. 1. 1. 1. 1.] 负理想解= [0.72       0.55555556 0.85714286 0.69230769 0.42857143 0.5       ]
[0.59538974 0.83163293 0.48540227 0.685136  ] [0.60245103 0.52529122 0.71826658 0.4144692 ]
TOPSIS的评价值为： [0.50294751 0.38711907 0.59673105 0.37692547]

关联系数= [[0.58823529 0.39130435 0.85714286 0.61111111 0.5        1.        ]
 [1.         1.         0.66666667 0.48148148 0.33333333 0.36363636]
 [0.50505051 0.52427184 1.         1.         1.         0.48780488]
 [0.70422535 0.46153846 0.85714286 0.74074074 0.5        0.36363636]] 
关联度= [0.6579656  0.64085297 0.75285454 0.6045473 ]

P=[[0.23529412 0.1875     0.25316456 0.23990158 0.25       0.37037037]
 [0.29411765 0.3375     0.2278481  0.20299364 0.15       0.18518519]
 [0.21176471 0.25       0.26582278 0.29321304 0.35       0.25925926]
 [0.25882353 0.225      0.25316456 0.26389174 0.25       0.18518519]]
,e=[0.99468893 0.98294821 0.99888759 0.9936177  0.97032272 0.96836882]
,g=[0.00531107 0.01705179 0.00111241 0.0063823  0.02967728 0.0